### ISSUE TITLE
Possibility to cancel sending while offline

### ISSUE THREAD

**Issue by bdimych** [schildbach/bitcoin-wallet#281]
Hi,
I sent coins when my phone was offline,
but I changed my mind and wanted to cancel.
Is it possible to stop this transaction while it is not yet sent to the network?

**Comment by schildbach** [comment]
Please use the community for user questions: https://plus.google.com/communities/105515929887248493912

**Comment by bdimych** [comment]
please wait, do not to close,
it was not just question but feature request,
I meant "I wanted to cancel but I couldn't do it and I thought about such feature",
I wrote it as question because I'm not sure is it ever possible in Bitcoin protocol to stop transaction

**Comment by schildbach** [comment]
Ok. It is not possible to cancel transactions reliably, because once a transaction is signed you never know who has got a copy of it. You say your phone was offline, but such an indication is often wrong. For example only the part of the internet might be unreachable for you. The other part will learn of your transaction and eventually it will confirm. Because of this uncertainty, I prefer not adding such a feature.

**Comment by bdimych** [comment]
Hmm, yes, if "bitcoin-offline" - I understand it is possible to do something not good,
but if this is real offline - when both wifi and mobile internet unavailable.

I'm traveling and in roaming, and I only have wifi inside my room,
when I'm outside I'm totally offline.
To be honest my case happened by my own mistake - I just forgot I am offline. And I agree this is quite rare case in real life.
But also such possibility looks not bad - to cancel transaction while smartphone is really system-offline.

ok, that's all, anyway thanks!
